name: Python application


on: [push]
>>>>>>> f59f7e1a5375a21df5daf3dcfee8e2ab076c48c5

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install bs4
        
    - name: Main
      run: |
        python main.py
        # stop the build if there are Python syntax errors or undefined names7 --statistics
>>>>>>> f59f7e1a5375a21df5daf3dcfee8e2ab076c48c5
